### ISSUE TITLE
getBestFitLayout not calculating layout size properly

### ISSUE THREAD

**Issue by ultracrepidarian** [fmtvp/tal#365] opened 2016-05-27 22:01 UTC
In _application.js_, the method `getBestFitLayout` sorts the layouts to find the largest applicable one.  It looks like it is sorting by screen diagonal size.  See the following code snippet

    133:  var ad = (a.width * a.width) + (a.height * b.height),
    134:      bd = (b.width * b.width) + (b.height * b.height);

But is the `(a.height * b.height)`, in the calculation for `ad`, a typo?  Shouldn't it be `(a.height * a.height)` ?

**Comment by LarsGrevelink** [comment] 2016-05-28 10:07
Hey!

We were wondering the same thing some time ago. You can find the thread here;
https://github.com/fmtvp/tal/issues/222

**Comment by AlexChesters** [comment] 2016-05-28 10:08
Closing as a duplicate of #222

**Comment by ultracrepidarian** [comment] 2016-05-30 10:46
Have we missed the step where this gets fixed?

Whether it's causing an immediate problem or not, isn't it customary to fix an issue before it does becomes a problem on down the line - when everyone's forgotten about it?

**Comment by AlexChesters** [comment] 2016-05-31 10:38
Hi @ultracrepidarian,
We’re reopening this as we intend to fix it. We will update this issue in due course but if you’d like to open a PR in the meantime please do!

**Comment by tsadler1988** [comment] 2016-09-29 10:01
Fixed by #400.

**Closed by tsadler1988** 2016-09-29 10:01 UTC
Labels: bug
