### ISSUE TITLE
How to test TAL app on Samsung or LG sdk ?

### ISSUE THREAD

**Issue by gabrielvieira** [fmtvp/tal#367] opened 2016-06-07 22:45 UTC

**Comment by AlexChesters** [comment] 2016-06-08 09:32
As per #281 (comment) we do not intend to document installation instructions for specific manufacturers as it can change year on year and by model, we would recommend that you use the official documentation. http://www.samsungdforum.com/ http://developer.lge.com/main/Intro.dev

Closing as a duplicate of #290.

**Closed by AlexChesters** 2016-06-08 09:32 UTC
