### ISSUE TITLE
require.def() does not work with recent versions of requireJS

### ISSUE THREAD

**Issue by ultracrepidarian** [fmtvp/tal#345] opened 2016-02-25 14:50 UTC
The TAL code uses require.def() in place of define().  Incorporating TAL into code which already uses requireJS exposes the problem above: requireJS no longer has require.def().  Even if the TAL's requireJS is deployed, the problem still impacts the build tools, e.g. jasmine's requirejs "template", and the requireJS optimiser/minifier.  There are ways round each issue, to be sure, but each one is a new kludge in the build.  Is there any reason require.def has been chosen in preference to define?  Would there be any impact if define is used instead?

**Comment by lukejpreston** [comment] 2016-02-25 15:11
our version of require is "0.15.0" (just checked in the browser ```require.version```). This version is not maintained anymore and you will be hard pressed to get information on it.

They should be behave the same

```define = req.def``` line 259 in our require module. In fact much of the new code we have been writing is defined instead of require.def and it would be easy to change the code to use define instead

And since the code is the same I don't see why we would need to do major regression testing (though I imagine we would anyway)

**Comment by AlexChesters** [comment] 2016-02-25 15:13
As @lukejpreston has pointed out, they should behave the same in `tal` [require.js#L255](https://github.com/fmtvp/tal/blob/master/static/script/lib/require.js#L255).

I'd like to see this raised as a tech debt issue that could be picked up, replacing instances of `require.def` with `define`

**Comment by lukejpreston** [comment] 2016-02-25 15:14
@AlexChesters  :+1:

**Comment by subsidel** [comment] 2016-02-25 15:23
Agreed, we should migrate to define.

**Closed** 2016-03-02 16:33 UTC
Labels: in progress, question, tech-debt
